kaldi-gstreamer-server:
  image: claritylab/lucida-asr:latest
  command: bash -c "cd /opt/kaldi-gstreamer-server/ && ./start.sh -y sample_english_nnet2.yaml && cd lucida-demos/ && python -m SimpleHTTPServer 8090"
  ports:
    - "8888:8888"
    - "8090:8090"
