apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: imm
  name: imm-controller
spec:
  replicas: 1
  selector:
    name: imm
  template:
    metadata:
      labels:
        name: imm
    spec:
      containers:
      - image: ybga/lucida
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/imagematching/opencv_imm/server/ && ./imm_server']
        name: imm
        ports:
        - containerPort: 8082
          name: thrift
